AWSTemplateFormatVersion: '2010-09-09'
Description: CloudMart IAM roles

Parameters:
  Environment:
    Type: String
    Default: prod

Resources:

  #############################################
  # Authorizer Execution Role
  #############################################

  AuthorizerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudMart-${Environment}-AuthorizerExecutionRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:

        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

        #######################################
        # SSM RBAC TOKEN ACCESS
        #######################################

        - PolicyName: ReadRBACTokens
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadRBACTokens
                Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/auth/admin-token
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/auth/products-token
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/auth/orders-token

        #######################################
        # VPC ENI
        #######################################

        - PolicyName: VPCNetworking
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'


  #############################################
  # Product Execution Role
  #############################################

  ProductExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudMart-${Environment}-ProductExecutionRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:

        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

        - PolicyName: ReadDatabasePassword
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/db/password

        - PolicyName: VPCNetworking
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'


  #############################################
  # Order Execution Role
  #############################################

  OrderExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudMart-${Environment}-OrderExecutionRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:

        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

        - PolicyName: ReadDatabasePassword
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/db/password

        - PolicyName: EventBridge
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: '*'

        - PolicyName: SNS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'

        - PolicyName: VPCNetworking
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'


  #############################################
  # Apply Schema Role
  #############################################

  ApplySchemaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudMart-${Environment}-ApplySchemaExecutionRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:

        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

        - PolicyName: ReadDatabasePassword
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloudmart/${Environment}/db/password

        - PolicyName: VPCNetworking
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'

Outputs:

  AuthorizerExecutionRoleArn:
    Value: !GetAtt AuthorizerExecutionRole.Arn

  ProductExecutionRoleArn:
    Value: !GetAtt ProductExecutionRole.Arn

  OrderExecutionRoleArn:
    Value: !GetAtt OrderExecutionRole.Arn

  ApplySchemaExecutionRoleArn:
    Value: !GetAtt ApplySchemaExecutionRole.Arn
